server:
  port: 9090
spring:
  application:
    name: user
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        cluster-name: beijing
#        namespace: 4e1d8706-0d03-4238-9586-21223be80733
order:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule

name: lisa
where: home
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10000/eureka  # 连接地址
#
#order:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#ribbon:
#  eager-load:
#    enabled: true # 开启饥饿加载
#    clients:
#      - order # 指定对user服务开启负载均衡