server:
  port: 11000
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      routes:
        - id: user-service
          uri: lb://user
          predicates:
            - Path=/user/**
        - id: order-service
          uri: lb://order
          predicates:
            - Path=/order/**
        - id: customer-service
          uri: lb://customer
          predicates:
            - Path=/customer/**
      default-filters:
        - AddRequestHeader=Truth, It is FireRain Request!
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:5050"
              - "http://localhost:6060"
            allowed-methods:
              - "POST"
              - "GET"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
            allowed-headers: "*"
            allow-credentials: true
            max-age: 360000