server:
  port: 10000
spring:
  application:
    name: eurekaserver  # 应用名称
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10000/eureka  # 连接地址
#    register-with-eureka: false  # 默认连接自己
#    fetch-registry: false # 默认连接别人